### ISSUE TITLE
issues with KDE version

### ISSUE THREAD

**Issue by neonramzy** [SpiralLinux/SpiralLinux-project#24] opened 2022-06-25 05:20 UTC
after fresh install:
no bluetooth function available ( bluedevil package needed)
plasma discover can not connect to internet(need to reinstall appstream-qt package)
some plasma widget  doesn't work properly(need to reinstall plasma widgets addons package)
no audio test feedback in plasma sound setting(need to install libcamberra-pulse package)
mobile broadband option in plasma setting  doesn't launch  and cause system freeze.
after waking up from suspend keyboard  doesn't work and need to reboot and reconfigure keyboard with dpkg(qt virtual keyboard and onboard packages are recommended)
kde partition manager or gparted packages are missing(partition operations preview before apply are not available in gnome disk)

**Comment by geckolinux** [comment] 2022-06-25 15:35
Hi there, thanks a lot for the useful feedback.

> no bluetooth function available ( bluedevil package needed)
Don't know I skipped over this one. Thanks! It will be included in the next release.

> plasma discover can not connect to internet(need to reinstall appstream-qt package)
The appstream package is kind of a secondary issue. Discover does work and it does connect to the internet, but it throws an erroneous "Can't connect" message when it is actually updating the appstream data. If you click on the "Fetching updates" button toward the bottom you'll see that it actually does work. I'm going to try preinstalling the `appstream-generator` package to see if that fixes it, but this might just be an unfixable issue with Discover. Fortunately it's not a serious issue.

> some plasma widget doesn't work properly(need to reinstall plasma widgets addons package)
I would need some more information on what isn't working. In general, in Linux reinstalling packages doesn't do anything as it simply replaces the same files that were already there.

> no audio test feedback in plasma sound setting(need to install libcamberra-pulse package)
Thanks, it's a [known issue](https://github.com/SpiralLinux/SpiralLinux-project/issues/23) and will be fixed in the next release.

> mobile broadband option in plasma setting doesn't launch and cause system freeze.
Thanks, I'll remove that from the next release. The mobile broadband functionality appears to work directly through the normal Plasma NetworkManager settings by adding a new connection of type Mobile Broadband.

> after waking up from suspend keyboard doesn't work and need to reboot and reconfigure keyboard with dpkg(qt virtual keyboard and onboard packages are recommended)
Unfortunately that sounds like an issue with the Debian kernel and your hardware, I can't reproduce it. Please try both the 5.10 and the 5.16 kernels provided by default in SpiralLinux. As for a virtual keyboard, `onboard` looks like it's fairly small, so it could be included by default.

> kde partition manager or gparted packages are missing(partition operations preview before apply are not available in gnome disk)
Thanks, `partitionmanager` looks good and doesn't take too much space.

**Comment by geckolinux** [comment] 2022-06-29 00:00
Implemented/fixed in 11.220628 release
https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/11.220628

**Closed by geckolinux** 2022-06-29 00:00 UTC
Labels: bug, enhancement, todo
