### ISSUE TITLE
Some questions about SpiralLinux

### ISSUE THREAD

**Issue by Vibhav201** [SpiralLinux/SpiralLinux-project#367] opened 2023-12-02 06:34 UTC
I was looking to use a Debian-based distro as my daily driver. I found the two best candidates to be MX Linux or Spiral Linux. I have some noobie questions about Spiral though:

1. Can I use Spiral with ext4 instead of btrfs? If yes, will the snapper configs and packages still be included in my install (because these will be bloat without btrfs)?

2. Can I use Spiral with standard swap with ZSWAP instead of ZRAM, I find ZSWAP to be more suitable for my 6GB RAM low-end laptop?

3. Can I use the same swap partition between Spiral and some other distro installation on my machine? Basically I want to dual boot Gecko Linux and Spiral Linux.

**Comment by geckolinux** [comment] 2023-12-02 13:07
Hi there,

1. Yes. I wouldn't be concerned about the Snapper packages (the configs won't be created in the case of EXT4) as they are very small, but if you want to you can also uninstall them.
2. Yes. Calamares will ask you what kind of swap you want (partition, file, or none) and then in the installed system you could run `sudo systemctl disable zramswap.service` .
3. Yes. You would need to use the custom manual partitioning mode of Calamares.

**Comment by geckolinux** [comment] 2023-12-02 13:08
Closing this issue since it's not a bug, but feel free to reply with additional questions.

**Closed as completed by geckolinux** 2023-12-02 13:08 UTC
Labels: not-a-bug

**Comment by Vibhav201** [comment] 2023-12-02 17:10
Thanks for this reply and thanks for the amazing work you're doing with Spiral and Gecko Linux. You're a genius basically. :)

**Comment by geckolinux** [comment] 2023-12-02 17:48
Thanks for saying so, I'm glad it's working well for you.
